name: Tag and Release after pre-prod merge

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Numéro de version (ex: v1.2.0)'
        required: true
        type: string
  push:
    branches:
      - pre-prod

jobs:
  create_tag_and_release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.ref == 'refs/heads/pre-prod' && github.event.before != '')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}